name: ravel
description: Share your travel experiences

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 0.4.4
  cloud_firestore: 0.13.4
  firebase_storage: ^3.1.3
  firebase_auth: 0.15.4
  rxdart: ^0.23.1
  geoflutterfire: ^2.1.0
  google_maps_flutter: ^0.5.24+1
  provider: ^4.0.4
  smooth_page_indicator: ^0.1.4
  geolocator: ^5.3.0
  multi_image_picker: ^4.6.3
  file_picker: ^1.4.3+2
  uuid: ^2.0.4
  flutter_full_pdf_viewer: ^1.0.6
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/


  fonts:
    - family: CatamaranBlack
      fonts:
        - asset: assets/fonts/catamaran/Catamaran-Black.ttf
    - family: CatamaranBold
      fonts:
        - asset: assets/fonts/catamaran/Catamaran-Bold.ttf
    - family: CatamaranExtraBold
      fonts:
        - asset: assets/fonts/catamaran/Catamaran-ExtraBold.ttf
    - family: CatamaranExtraLight
      fonts:
        - asset: assets/fonts/catamaran/Catamaran-ExtraLight.ttf
    - family: CatamaranLight
      fonts:
        - asset: assets/fonts/catamaran/Catamaran-Light.ttf
    - family: CatamaranMedium
      fonts:
        - asset: assets/fonts/catamaran/Catamaran-Medium.ttf
    - family: CatamaranRegular
      fonts:
        - asset: assets/fonts/catamaran/Catamaran-Regular.ttf
    - family: CatamaranSemiBold
      fonts:
        - asset: assets/fonts/catamaran/Catamaran-SemiBold.ttf
    - family: CatamaranThin
      fonts:
        - asset: assets/fonts/catamaran/Catamaran-Thin.ttf
    - family: OpenSansBold
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
    - family: OpenSansExtraBold
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
    - family: OpenSansLight
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
    - family: OpenSansRegular
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
    - family: OpenSansSemiBold
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf

